logging:
  level:
    org:
      springframework: INFO

spring:
  profiles:
    active: production

server:
  port: ${PORT:5000}

expedia:
  url: https://offersvc.expedia.com/offers/v2/getOffers?scenario=deal-finder&page=foo&uid=foo&productType=Hotel