logging:
  level:
    org:
      springframework: INFO
    com:
      muayadsalah:
        client:
          ExpediaClient: INFO

spring:
  profiles:
    active: production
  application:
    name: HotelDeals

server:
  port: ${PORT:5000}

expedia:
  url: https://offersvc.expedia.com/offers/v2/getOffers?scenario=deal-finder&page=foo&uid=foo&productType=Hotel
  response:
    json:
      node:
        offers: offers
        hotels: Hotel